### ISSUE TITLE
Add option to merge lanes from sequencing

### ISSUE THREAD

**Issue by signeskog** [Danis102/seqpac#23]
When downloading FASTQ-files from BaseSpace Downloader, files does not automatically merge together from lanes. We should add lane merge prior to counts in make_counts, to make the trimming and counts flow streamlined for some Windows users.

**Comment by Danis102** [comment]
This feature is included in the latest update to development branch, and will soon also be merged with the master branch. Please use the merge_lanes function before running the make_counts function. The merge_lanes function will merge fastq files with similar names. Thus you have to make sure that some part of the beginning of the file name is identical across lane files that should be merged (e.g. sample1_lane1.fastq, sample1_lane2.fastq, sample2_lane1.fastq etc.  )
