### ISSUE TITLE
 invalid class “SRFilterResult” object: 

### ISSUE THREAD

**Issue by JIBINJOHNV** [Danis102/seqpac#31]
I would appreciate if you could look at the following issues that I encountered during my analysis:

## Comman used
path_to_fastq <- system.file("extdata", package = "seqpac", mustWork = TRUE)
count_list <- make_counts(input=path_to_fastq, type = "fastq", trimming="seqpac", 
                          parse="default_neb")

## Error
Identifying unique sequences in trimmed fastq files ...Error in { :
  task 1 failed - "error in evaluating the argument 'object' in selecting a method for function 'sread': Input/Output
  file(s):
    /tmp/Rtmp5BnlP2/seqpac//Stage1_Batch1_Inx3_S3.trim.fastq.gz
  message: IncompatibleTypes
  message: error in evaluating the argument 'i' in selecting a method for function '[': invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class"

**Comment by Danis102** [comment]
Sorry for a late response. We will try getting back sooner in the future. 

We have not encounter this issue on our test machines. After quickly googling around, it seems that similar errors have occurred for other packages when running some versions of Matrix (for example see: https://github.com/benjjneb/dada2/issues/212#issuecomment-836757295)

Try update the ShortReads package or downgrade the Matrix package  to an older version. You may also try our development branch, in case this issue has been solved by recent updates in seqpac.
