### ISSUE TITLE
No Hit and undefined columns

### ISSUE THREAD

**Issue by kittyBS** [Danis102/seqpac#42]
Hello,
I'm having some problems with the analysis;
1. When I start the analysis with my trimmed samples, it does not detect any hits with the tRNA and miRNA I indexed in the analysis.
2. How can I index multiple tRNA fasta files as a single reference?
3. How can I make this classification for miRNA in the "Hierarchical classification with simplify_reanno" step?
4. In the "Simple stacked bars and pie charts" section, in the PAC_stackbar(pac, anno_target=list("Biotypes_mis0")) code, there is "Error in `[.data.frame`(PAC$Anno, , anno_target[[1]]) :
   I can't get past the "undefined columns selected" error.

I'm adding my codes and reference data to help you. Thank you in advance for your help.
The reference data I used is from https://ncrnainfo-my.sharepoint.com/personal/sports_ncrna_info/_layouts/15/guestaccess.aspx?docid=0833653a140eb47f098267d7a23d3b63c&authkey=Ab8aoYC8paqFI2yRabIo7Ok
[seqpac.txt](https://github.com/Danis102/seqpac/files/14179478/seqpac.txt)
[sample.txt](https://github.com/Danis102/seqpac/files/14179504/sample.txt)

**Comment by signeskog** [comment]
Hello,

Thank you very much for the code snippet! 
When running make_counts, I see that trimming=NULL, which will override parse="default_neb" and ignore the trimming step. I wonder if this could be the case of the low mapping rate, as adaptors may still be present in the sequences and disturb the mapping. 

Regarding number 2 and 3, this is the way I would add your different tRNA references, which will make the end result that they will be classified as tRNA biotype no matter which of the fasta reference files they are found in:

```
map_reanno(pac,
ref_paths=list(tRNA_1=" /archive/yildize/alotaibi_lab/smrnaseq/Elf5_KD/unzipdata/Mus_musculus/GtRNAdb/mm10/mm10-mature-tRNAs.fa", 
tRNA_2=" /archive/yildize/alotaibi_lab/smrnaseq/Elf5_KD/unzipdata/Mus_musculus/GtRNAdb/mm10/mm10-mt_tRNAs_CCA.fa", 
tRNA_3=" /archive/yildize/alotaibi_lab/smrnaseq/Elf5_KD/unzipdata/Mus_musculus/GtRNAdb/mm10/mm10-mt_tRNAs.fa",
tRNA_4= " /archive/yildize/alotaibi_lab/smrnaseq/Elf5_KD/unzipdata/Mus_musculus/GtRNAdb/mm10/mm10-tRNAs.fa",
                          miRNA=" /archive/yildize/alotaibi_lab/smrnaseq/Elf5_KD/unzipdata/Mus_musculus/miRBase/21/miRBase_21-mmu.fa"), 
           output_path= outpath_biotype,  
import="biotype")
 
reanno_biotype <- make_reanno(reanno_path= outpath_biotype,
                              PAC=pac, 
                              mis_fasta_check = TRUE)
 
bio_search <- list(tRNA_1= c("_tRNA", "mt:tRNA"),
tRNA_2= c("_tRNA", "mt:tRNA"),
tRNA_3= c("_tRNA", "mt:tRNA"),
tRNA_4= c("_tRNA", "mt:tRNA"),
                   miRNA=c("mir-", "mmu-mir","hsa-miR-")))
 
pac <- add_reanno(reanno_biotype, 
bio_search=bio_search, 
                    type="biotype", bio_perfect=TRUE, 
                    mismatches = 3, merge_pac=pac)
 
pac<-simplify_reanno(input=pac, 
                       hierarchy = list(miRNA="miRNA",
tRNA=" tRNA_1_tRNA|tRNA_1_mt:tRNA tRNA_2_tRNA|tRNA_2_mt:tRNA tRNA_3_tRNA|tRNA_3_mt:tRNA tRNA_4_tRNA|tRNA_4_mt:tRNA")
                       mismatches = 3,
                       merge_pac=TRUE,
                       bio_name = "Biotypes_3mm")
```


It is in the last step of simplify_reanno where you define that miRNA is above tRNA in this case. 

Regarding your question 4, according to the code you sent there is no where when simplify_reanno is ran "back" into the original pac object (with merge_pac=TRUE). I believe that is why your pac object lacks the "Biotypes_mis0"-column. If you would run 

`PAC_stackbar(pac_test, anno_target=list("Biotypes_mis1"))`

that could work instead, as you do add the Biotypes_mis1 back into that pac object! 

I hope this makes sense, and if you would need more help or clarification please feel free to reach out here or through e-mail (signe.skog@liu.se)!

All the best,
Signe

**Comment by kittyBS** [comment]
Thank you for your quick and descriptive response.
After your instructions, I still get some errors, but I believe I will solve it.
Best regards
